# Generated by Django 5.2.3 on 2025-07-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0003_tag_song_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='tags',
        ),
        migrations.AddField(
            model_name='singer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='singer.tag'),
        ),
    ]
