# Generated by Django 5.2.3 on 2025-07-03 17:53

import singer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0004_remove_song_tags_singer_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=singer.models.image_upload_path),
        ),
    ]
