# Generated by Django 5.2.3 on 2025-07-13 15:10

import django.db.models.deletion
import singer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0005_singer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingerImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=singer.models.singer_image_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='singer.singer')),
            ],
        ),
    ]
